import { StyleSheet } from "react-native";

/* ─────────── THEMES & STYLES ─────────── */
const LIGHTTHEME = { bg: '#F5F3FF', card: '#FFFFFF', text: '#1a1a2e', subtext: '#6B7280', border: '#E9D5FF' };
const DARKTHEME = { bg: '#15131F', card: '#221E33', text: '#F3F4F6', subtext: '#8B85A0', border: '#2E2942' };

const makeStyles = (A) => StyleSheet.create({
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10 },
  logoIcon: { width: 36, height: 36, borderRadius: 11, backgroundColor: A, alignItems: 'center', justifyContent: 'center' },
  ptsBadge: { backgroundColor: '#FF6B35', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 18 },
  gearBtn: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 26, fontWeight: '800' },
  sub: { fontSize: 13, marginTop: 2 },
  sectionLabel: { fontSize: 11, fontWeight: '800', letterSpacing: 0.5, marginVertical: 8 },
  pill: { paddingHorizontal: 13, paddingVertical: 7, borderRadius: 18 },
  clubCard: { borderRadius: 22, padding: 20, minHeight: 240, justifyContent: 'flex-end', marginTop: 4 },
  clubTag: { backgroundColor: 'rgba(255,255,255,0.25)', alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12, marginBottom: 8 },
  clubName: { fontSize: 24, fontWeight: '800', color: 'white', marginBottom: 4 },
  clubDesc: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginBottom: 10 },
  metaPill: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  metaPillText: { color: 'white', fontSize: 11, fontWeight: '600' },
  actionBtn: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', elevation: 3, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 6, shadowOffset: { width: 0, height: 3 } },
  addBtn: { width: 42, height: 42, borderRadius: 13, backgroundColor: A, alignItems: 'center', justifyContent: 'center' },
  dayCell: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 12, gap: 3 },
  dot: { width: 5, height: 5, borderRadius: 3 },
  eventCard: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 14, padding: 12, marginBottom: 8 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 9 },
  buildingCard: { borderRadius: 16, padding: 14 },
  friendChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 14 },
  clubRow: { flexDirection: 'row', alignItems: 'center', paddingTop: 10, marginTop: 10, borderTopWidth: 1 },
  heroCard: { backgroundColor: A, borderRadius: 22, padding: 18 },
  heroAvatar: { width: 54, height: 54, borderRadius: 27, backgroundColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: 'rgba(255,255,255,0.4)' },
  upgradeBanner: { flexDirection: 'row', alignItems: 'center', borderRadius: 14, padding: 12, marginTop: 12 },
  upgradeBtn: { backgroundColor: '#FF6B35', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 11 },
  tabBtn: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 12 },
  badgeCard: { width: '47.5%', borderRadius: 14, padding: 12, alignItems: 'center' },
  leaderRow: { flexDirection: 'row', alignItems: 'center', borderRadius: 12, padding: 12, marginBottom: 8 },
  rewardRow: { flexDirection: 'row', alignItems: 'center', borderRadius: 14, padding: 12, marginBottom: 8 },
  redeemBtn: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 11 },
  friendRow: { flexDirection: 'row', alignItems: 'center', borderRadius: 14, padding: 11, marginBottom: 8 },
  avatar: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  postCard: { borderRadius: 16, padding: 13, marginBottom: 10 },
  ctaBtn: { borderRadius: 11, paddingVertical: 9, alignItems: 'center', marginTop: 4 },
  tabBar: { flexDirection: 'row', paddingHorizontal: 8, paddingTop: 7, paddingBottom: 7, borderTopWidth: 1 },
  navBtn: { flex: 1, alignItems: 'center', paddingVertical: 6, borderRadius: 12, gap: 1 },
  toast: { position: 'absolute', bottom: 90, alignSelf: 'center', backgroundColor: '#1a1a2e', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18, maxWidth: '88%' },
  modalWrap: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 20, maxHeight: '88%' },
  handle: { width: 40, height: 4, borderRadius: 3, alignSelf: 'center', marginBottom: 14 },
  sheetEmoji: { fontSize: 42, textAlign: 'center' },
  sheetTitle: { fontSize: 22, fontWeight: '900', textAlign: 'center', marginTop: 4 },
  sheetSub: { fontSize: 13, textAlign: 'center', marginTop: 4, marginBottom: 12, lineHeight: 19 },
  bigBtn: { backgroundColor: A, borderRadius: 14, paddingVertical: 14, alignItems: 'center', marginTop: 12 },
  bigBtnText: { color: 'white', fontSize: 15, fontWeight: '800' },
  skipText: { textAlign: 'center', fontSize: 13, paddingVertical: 11 },
  fine: { fontSize: 10, textAlign: 'center', opacity: 0.7 },
  input: { borderRadius: 13, borderWidth: 1.5, paddingHorizontal: 13, paddingVertical: 11, fontSize: 14, marginBottom: 10 },
  label: { fontSize: 11, fontWeight: '800', letterSpacing: 0.5, marginBottom: 6, marginTop: 4 },
  dayPick: { flex: 1, paddingVertical: 8, borderRadius: 10, borderWidth: 1, alignItems: 'center', marginBottom: 10 },
  colorDot: { width: 32, height: 32, borderRadius: 16, marginBottom: 10 },
  causeRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderRadius: 13, padding: 13, marginBottom: 8 },
  codeBox: { borderWidth: 2, borderStyle: 'dashed', borderRadius: 14, padding: 16, alignItems: 'center', marginTop: 6 },
  plannerBlock: { borderRadius: 14, padding: 13, marginBottom: 10 },
  chatHeader: { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1 },
  msgThem: { alignSelf: 'flex-start', maxWidth: '75%', borderRadius: 16, borderBottomLeftRadius: 5, padding: 11 },
  msgMe: { alignSelf: 'flex-end', maxWidth: '75%', backgroundColor: A, borderRadius: 16, borderBottomRightRadius: 5, padding: 11 },
  chatBar: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 10, borderTopWidth: 1 },
  chatInput: { flex: 1, borderRadius: 20, paddingHorizontal: 15, paddingVertical: 10, fontSize: 14 },
  sendBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: A, alignItems: 'center', justifyContent: 'center' },
  setCard: { borderRadius: 14, overflow: 'hidden', marginBottom: 6 },
  setRow: { flexDirection: 'row', alignItems: 'center', padding: 13 },
});

export { LIGHTTHEME, DARKTHEME, makeStyles };
